### ISSUE TITLE
Remove use of CustomData in the code

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/Filing_Toolkit#82]
The files listed below have been detected as having code using `CustomData`. This detection has been automatic, and may have picked up on code comments or documentation. Please review each file carefully and remove all instances of `CustomData`.

This should be completed by the 30th October 2020.

<details>
<summary>Full list</summary>
<p>

 - [ ] Filing_Toolkit\Filing_Adapter\CRUD\Read\ReadFileContent.cs

 - [ ] Filing_Toolkit\Filing_Engine\Convert\ToFiling\FSDirectory.cs

 - [ ] Filing_Toolkit\Filing_Engine\Convert\ToFiling\FSFile.cs

</p>
</details>

**Comment by alelom** [comment]
No problem for FSDirectory.cs and FSFile.cs.

However ReadFileContent.cs has to read CustomData to check whether there is relevant information there to be Read, so it has to stay.
